name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install distutils
      run: |
        sudo apt-get update
        sudo apt-get install python3-distutils
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt

    - name: Run tests
      run: |
        pytest -s -v tests/dataset_conversion_test/tests_coco_creation_dataset.py
        pytest -s -v tests/dataset_conversion_test/tests_yolo_creation_dataset.py
        pytest -s -v tests/dataset_conversion_test/tests_coco_to_yolo.py
        pytest -s -v tests/dataset_conversion_test/tests_yolo_to_coco.py
        pytest -s -v tests/test_image_preprocessing/test_object_detection.py
        pytest -s -v tests/test_model_for_classification/test_transformers_without_adapter_for_classification.py
